---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: typescript-hello-world
  annotations:
    version: v0.0.3
    description: "Demo of Typescript HTTP hello world server"
spec:
  components:
    # (Component) A test component that returns a string for any given HTTP request
    - name: http-component
      type: component
      properties:
        image: file://./dist/http-hello-world.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: calc-component
            namespace: wasmcloud
            package: hello
            interfaces: [calculator]
        - type: link
          properties:
            target: kvredis
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target_config:
              - name: redis-url
                properties:
                  url: redis://127.0.0.1:6379

    # (Component) A test component that returns a string for any given HTTP request
    - name: calc-component
      type: component
      properties:
        image: file://./dist/calc.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1

    # The new capability provider
    - name: kvredis
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.24.0
    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
