package wasmcloud:hello;

interface calculator {
  calculatesum: func(x: u32, y: u32) -> u32;
}

world calc {
  export calculator;
}

world hello {
  import calculator;

  export wasi:http/incoming-handler@0.2.0;
}
